### ISSUE TITLE
PHP syntax error in version.php

### ISSUE THREAD

**Issue by mudrd8mz** [middlebury/Moodle-auth_casattras#5]
The code `$plugin->release   = 1.0.0;` leads to

```
Parse error: syntax error, unexpected '.0' (T_DNUMBER) in auth/casattras/version.php on line 30
```

on plugin installation (which may have fatal impact on the whole site functionality). You probably want to put the release number into quotes.

**Comment by adamfranco** [comment]
This has been fixed for a while, so closing this issue. Thanks for reporting!
